engines:
  fixme:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript:

ratings:
  paths:
   - "dist/*"
exclude_paths:
  - node_modules/
  - screepsAutocomplete
