env:
  node: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'screeps-neat-o'
parserOptions:
  sourceType: module
globals:
  '_': false
rules:
  no-console: 0
  indent:
    - warn
    - 2
    - SwitchCase: 1
  max-len:
    - warn
    - code: 80
    - tabWidth: 2
  complexity:
    - error
    - 10
